FROM dunglas/frankenphp

RUN apt-get update && apt-get install -y \
    git \
    unzip \
    zip \
    libzip-dev \
    libpq-dev \
    procps \
    && docker-php-ext-install pdo pdo_pgsql pgsql zip \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /app

RUN chown -R www-data:www-data /app

EXPOSE 443

CMD ["frankenphp", "run", "--config", "/etc/caddy/Caddyfile"]